### ISSUE TITLE
Add gallery page

### ISSUE THREAD

**Issue by riittagerhards** [riittagerhards/dear-diary#10]
**Description:**

The user gets a list view of all entries she/he generated in the given month. A single card displays the date of the entry and the image. If no image is uploaded, card displays the text input. The user can scroll down the page. On the bottom of the page is a button to go back to top. The header shows the month, which the user can set with a dropdown. If no month is selected, default is the current month.

**Screenshot:**

![image](https://user-images.githubusercontent.com/91462609/142999648-9740d112-6004-4827-bc4a-3bc2c97ff0a0.png)

**Tasks:**

- [x] Add header component with static "Gallery", dropdown to set the month and page navigation bar
- [x] Create and add card component
- [x] Fetch function to get the entries of given month and fill the cards
- [x] Function onClick on a card to move from one date to show the content on "single entry" page

**Acceptance criteria:**

- none: if no month is chosen, gallery displays the current month
