### ISSUE TITLE
Add single entry page

### ISSUE THREAD

**Issue by riittagerhards** [riittagerhards/dear-diary#11]
**Description:**

User sees the entry of the day as she/he uploaded it. If there is no image, the card shows a placeholder. If no text is uploaded, the text card shows a placeholder text. The date is displayed in header, the title between image and text card. User has the option to edit or delete the entry with buttons on the bottom of the page.

**Screenshot:**

![image](https://user-images.githubusercontent.com/91462609/143005526-974e249e-bcc0-49a0-b318-6c34cd681b52.png)

**Tasks:**

- [x] Add header component to display the chosen date, with page navigation
- [x] Insert image title and text
- [x] Function to get the displayed information from fetch
- [x] Add button component for edit and delete
- [x] Function to delete a diary entry

**Acceptance criteria:**

- none: the page shows information of the chosen date. You can see the entry only by clicking a date in the gallery or in the calendar on the home page.
