### ISSUE TITLE
Add Welcome page

### ISSUE THREAD

**Issue by riittagerhards** [riittagerhards/dear-diary#6]
**Description:**

In the app, there is no login but the user needs to enter her/his name on the welcome page to use the app

**Screenshots:**

![image](https://user-images.githubusercontent.com/91462609/142909240-6ffe7d36-82bc-45dc-a15e-8fe442c5fd77.png)

**Tasks:**

- [x] create app logo component
- [x] add background image
- [x] create text input field with onSubmit function
- [x] text input should trigger the header on the Home page with useState

**Acceptance criteria:**

- an input is required
- max. 15 letters
