### ISSUE TITLE
Add Home page

### ISSUE THREAD

**Issue by riittagerhards** [riittagerhards/dear-diary#7]
**Description:**

The user sees her/his name in the page header with a welcome text. In the header the user finds a page navigation. The home page shows a calendar with the date of the day as default. User can add a new diary entry by clicking on the add icon. The page also displays a calendar with a monthly view. Days with diary entries are highlighted and the user can access the date by clicking on it. It's also possible to change the month in calendar with drop menu.

**Screenshot:**

![image](https://user-images.githubusercontent.com/91462609/142910537-b84b499e-879d-42a8-a583-6034eaea5eb9.png)

**Tasks:**

- [x] Add a header component
- [x] Add a page navigation
- [x] Set the header to display the name set on the Welcome page
- [x] Add a card component with a display of the current date and an onClick icon
- [x] Add a calendar component with monthly view and a drop menu to change the month
- [x] Add a function to highlight dates with diary entries, this needs a fetch from MongoDB

**Acceptance criteria:**

- none: if nothing is selected, the card displays the current date and calendar shows the current month
