### ISSUE TITLE
Add the add entry page

### ISSUE THREAD

**Issue by riittagerhards** [riittagerhards/dear-diary#9]
**Description:**

From the welcome page the user lands on the "add" page to add a new diary entry.  The user can upload an image, set the date in dropdown (default is current date), add a title for the entry and type a short notice. A save button uploads the image to mongoDB.

**Screenshot:**

![image](https://user-images.githubusercontent.com/91462609/142990757-885c1eb1-c100-4995-b2fd-a8e98c219e56.png)

**Tasks:**

- [x] Connect MongoDB
- [x] Add form element for different inputs
- [x] Add input fields for image upload, date, title and text
- [x] Add cloudinary for image upload
- [x] Add a save button with onSubmit to push the content to mongoDB
- [x] Add header component with static title "How was your day?" and navigation bar

**Acceptance criteria:**

- Required inputs: date, title, image or text
- max length for the title needs to be set, maybe 50
- Max length for the text input needs to be set, maybe 250
